### ISSUE TITLE
'Last 2 dimensions of the array must be square'

### ISSUE THREAD

**Issue by caxavier** [alkaline-ml/pmdarima#341] opened 2020-06-05 16:33 UTC
Hi,

I have been using your program pmdarima to calculate forecast models.
Here is the arguments that I use:

```python
smodel = pm.auto_arima(Train['Count'], start_p=1, start_q=1,
                               test='adf',
                               max_p=3, max_q=3, m=52,
                               start_P=0, seasonal=True,
                               d=None, D=1, trace=True,
                               error_action='ignore',  
                               suppress_warnings=True, 
                               stepwise=True)
```

Recently I've came up with an error when I run it with a specific set of data.
              
```
  File "C:\Users\carolina.xavier\AppData\Roaming\Python\Python37\site-packages\pmdarima\arima\auto.py", line 436, in auto_arima
    d = ndiffs(dx, test=test, alpha=alpha, max_d=max_d, **offset_test_args)
  File "C:\Users\carolina.xavier\AppData\Roaming\Python\Python37\site-packages\pmdarima\arima\utils.py", line 165, in ndiffs
    pval, dodiff = testfunc(x)
  File "C:\Users\carolina.xavier\AppData\Roaming\Python\Python37\site-packages\pmdarima\arima\stationarity.py", line 338, in should_diff
    res = self._ols(x, y, z, k)
  File "C:\Users\carolina.xavier\AppData\Roaming\Python\Python37\site-packages\pmdarima\arima\stationarity.py", line 296, in _ols
    return sm.OLS(yt, X, hasconst=True).fit(method='qr')
  File "C:\Users\carolina.xavier\AppData\Roaming\Python\Python37\site-packages\statsmodels\regression\linear_model.py", line 332, in fit
    beta = np.linalg.solve(R, effects)
  File "<__array_function__ internals>", line 6, in solve
  File "C:\Users\carolina.xavier\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\linalg\linalg.py", line 387, in solve
    _assert_stacked_square(a)
  File "C:\Users\carolina.xavier\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\linalg\linalg.py", **line 214, in _assert_stacked_square
    raise LinAlgError('Last 2 dimensions of the array must be square')
numpy.linalg.LinAlgError: Last 2 dimensions of the array must be square**
```

The data is weekly an has 1 year and 4 months of data represented (1-Jan-2015 to 30-April-2020).
The train has length = 56.

But when we add another month (until the end of May), everything works fine.

Also, when we took one month (data is until end of March), the program complains about the value of D  and after we change it from 1 to 0, everything works fine again.

But we the data that we have , even by changing D, this error always appears.

Here is the data (prior transformation from daily to weekly).
[Data.xlsx](https://github.com/alkaline-ml/pmdarima/files/4737390/Data.xlsx)

**Comment by tgsmith61591** [comment] 2020-06-08 21:11
Thanks for the report, let me dig into this and get back to you

**Comment by tgsmith61591** [comment] 2020-06-10 10:46
Ok I got a chance to look into this. The short answer is that your train set appears to be too small for such a large `m`. Stepping through the code, when `D` is 1 and we difference your array we end with with a training series of length 4:

```python
    if D > 0:
        dx = diff(xx, differences=D, lag=m)
    # array([ 124., -114., -163.,  -83.])
```

And when it comes time to find `d`, we further difference the array so that by the time we actually fit the OLS regression in the ADF test it's fitting on 2 samples. Here are the y and X that end up getting fed [to the OLS](https://github.com/alkaline-ml/pmdarima/blob/master/pmdarima/arima/stationarity.py#L296):

```
In [71]: yt
Out[71]: array([-49.,  80.])

In [72]: X
Out[72]:
array([[   1., -114.,    2., -238.],
       [   1., -163.,    3.,  -49.]])
```

The OLS code is where things blow up. My guess is simply that the train size is too small for such a large `m` value, as it gets differenced down to very few samples.

**Comment by tgsmith61591** [comment] 2020-06-10 10:50
Alternatively, the default `kpss` test is able to test stationarity on your training set without any problems:

```python
In [99]: smodel = pm.auto_arima(Train['Count'], start_p=1, start_q=1,
    ...:                                test='kpss',
    ...:                                max_p=3, max_q=3, m=52,
    ...:                                start_P=0, seasonal=True,
    ...:                                d=None, D=1, trace=True,
    ...:                                error_action='ignore',
    ...:                                suppress_warnings=True,
    ...:                                stepwise=True)
Performing stepwise search to minimize aic
Fit ARIMA(1,0,1)x(0,1,1,52) [intercept=True]; AIC=nan, BIC=nan, Time=nan seconds
Fit ARIMA(0,0,0)x(0,1,0,52) [intercept=True]; AIC=52.914, BIC=51.687, Time=0.085 seconds
Fit ARIMA(1,0,0)x(1,1,0,52) [intercept=True]; AIC=56.852, BIC=54.398, Time=2.361 seconds
Near non-invertible roots for order (1, 0, 0)(1, 1, 0, 52); setting score to inf (at least one inverse root too close to the border of the unit circle: 0.999)
Fit ARIMA(0,0,1)x(0,1,1,52) [intercept=True]; AIC=nan, BIC=nan, Time=3.042 seconds
Fit ARIMA(0,0,0)x(0,1,0,52) [intercept=False]; AIC=51.935, BIC=51.321, Time=0.249 seconds
Fit ARIMA(0,0,0)x(1,1,0,52) [intercept=True]; AIC=54.913, BIC=53.072, Time=0.770 seconds
Fit ARIMA(0,0,0)x(0,1,1,52) [intercept=True]; AIC=54.885, BIC=53.044, Time=2.421 seconds
Near non-invertible roots for order (0, 0, 0)(0, 1, 1, 52); setting score to inf (at least one inverse root too close to the border of the unit circle: 0.997)
Fit ARIMA(0,0,0)x(1,1,1,52) [intercept=True]; AIC=56.884, BIC=54.429, Time=4.564 seconds
Near non-invertible roots for order (0, 0, 0)(1, 1, 1, 52); setting score to inf (at least one inverse root too close to the border of the unit circle: 0.999)
Fit ARIMA(1,0,0)x(0,1,0,52) [intercept=True]; AIC=54.905, BIC=53.064, Time=0.581 seconds
Fit ARIMA(0,0,1)x(0,1,0,52) [intercept=True]; AIC=nan, BIC=nan, Time=0.500 seconds
Fit ARIMA(1,0,1)x(0,1,0,52) [intercept=True]; AIC=nan, BIC=nan, Time=0.653 seconds
Total fit time: 24.058 seconds
```

**Comment by caxavier** [comment] 2020-06-18 13:55
Hi Taylor,

Thank you for your explanation!
I still have a few questions if you don't mind:

- Can you tell me what's the minimum of history of data for daily, weekly and monthly forecasts, for diferent tests?

-My data is regarding incoming calls, so it experiences a seasonality throughout the year. So what would be the better test to use?

- I had another issue (represented in image below), running a monthly forecast with this data: 
[rawdata.xlsx](https://github.com/alkaline-ml/pmdarima/files/4798897/rawdata.xlsx)



<img width="439" alt="Capture" src="https://user-images.githubusercontent.com/44777886/85028815-76c1f700-b173-11ea-8a0d-4fd76f52a47b.PNG">

**Comment by tgsmith61591** [comment] 2020-06-24 12:53
No problem.

> Can you tell me what's the minimum of history of data for daily, weekly and monthly forecasts, for diferent tests?

It is tough to give an exact answer to this, since the value of `D` is generally unknown at the time of `auto_arima`. In your case, a large enough `D` was selected to make the ADF test fail, where a smaller one would not have.

> My data is regarding incoming calls, so it experiences a seasonality throughout the year. So what would be the better test to use?

In general, I would recommend the default, which is `kpss`

> I had another issue (represented in image below), running a monthly forecast with this data:

Could you please provide the code that led to that error?

**Comment by tgsmith61591** [comment] 2020-06-24 12:54
Also, I think it may be a good idea for us to catch the `Last 2 dimensions` error and raise a more meaningful error.

**Comment by caxavier** [comment] 2020-06-30 16:11
Hi,

Regarding the error:
The data is converted to weekly and has 67 weeks. These historical data are divided into Train (54 train weeks) and valid (13 fixed test weeks). So same process for the remaining files, where the valid is always fixed in 13 weeks.
We tested these historical data using adf test and kpss test to try to find the minimum historical limit to use. The historical data are on sheet 1 and the errors we found are on sheet 2 of each excel file.

[Test_sarima.zip](https://github.com/alkaline-ml/pmdarima/files/4853085/Test_sarima.zip)


I don't know if I understood the above messages correctly. So you changed the error messages in the code to give a better explanation of the issue, is that it?
So I should download the pmdarima code again?

**Comment by tgsmith61591** [comment] 2020-06-30 17:33
With only 67 weeks and a periodicity of 52, it's a bit tricky. The default stationarity test (`kpss`) did not raise the error you encountered, so you should use that. I will look at your other issues, but they're probably similarly related.

To clarify my above comment, I've merged a better error handler into master, but we've not yet cut a new release. Release 1.7.0 will contain the changes soon, but is not publicly available yet.

**Comment by tgsmith61591** [comment] 2020-07-21 13:27
Closing due to inactivity. If there are any other questions, we can reopen or create a new issue.

**Closed by tgsmith61591** 2020-07-21 13:27 UTC
Labels: :grey_question: : question
