### ISSUE TITLE
negative dimensions are not allowed

### ISSUE THREAD

**Issue by srayagarwal** [alkaline-ml/pmdarima#327] opened 2020-04-26 11:58 UTC
**Describe the bug**
When using auto_arima
getting the bug
ValueError: negative dimensions are not allowed

```python
model=pm.auto_arima(value, exogenous=Texogenous, 
                    seasonal=True, m=4, supress_warnings=True, stepwise=True, approximation = True, error_action='ignore').fit(value, exogenous=Texogenous)
```

**Versions**

Darwin-18.7.0-x86_64-i386-64bit
Python 3.7.3 (default, Mar 27 2019, 16:54:48) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
pmdarima 1.3.0
NumPy 1.16.2
SciPy 1.2.1
Scikit-Learn 0.21.1
Statsmodels 0.11.0

**Comment by tgsmith61591** [comment] 2020-04-26 18:00
Looks like you're running a pretty old version of the package. This is a duplicate of #191 and [was fixed in 1.4.0](http://alkaline-ml.com/pmdarima/whats_new.html#id16). If you upgrade, it should be fixed.

**Closed by tgsmith61591** 2020-04-26 18:00 UTC
Labels: :beetle: : bug

**Comment by srayagarwal** [comment] 2020-04-26 18:13
I installed the package today
And also
Pip -upgrade pmdarmia too today

Any particular way u want me to upgrade or install the package?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by aaronreidsmith** [comment] 2020-04-26 18:19
What did you use to install it? And when you attempted to upgrade, did you use the correct command?

```
pip install —upgrade pmdarima
```

If the above doesn’t work, you can always specify the [latest version](https://pypi.org/project/pmdarima).

```
pip install "pmdarima==1.5.3"
```
