### ISSUE TITLE
Cannot install package pmdarima through pip

### ISSUE THREAD

**Issue by pcpankaj** [alkaline-ml/pmdarima#562] opened 2023-10-21 18:41 UTC
### Describe the bug

Cannot install pmdarima through pip with numpy version 1.26

### To Reproduce

pip install pmdarima

Python version 3.12.0
numpy 1.26

### Versions

```shell
Windows-11-10.0.22621-SP0
Python 3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)]
NumPy 1.26.1
SciPy 1.11.3
Scikit-Learn 1.3.1
Statsmodels 0.14.0
```

### Expected Behavior

Package should install

### Actual Behavior

See the output of installation in the additional context window

### Additional Context

Downloading Cython-3.0.4-cp312-cp312-win_amd64.whl (2.8 MB)
   ---------------------------------------- 2.8/2.8 MB 22.2 MB/s eta 0:00:00
Downloading joblib-1.3.2-py3-none-any.whl (302 kB)
   ---------------------------------------- 302.2/302.2 kB ? eta 0:00:00
Downloading numpy-1.26.1-cp312-cp312-win_amd64.whl (15.5 MB)
   ---------------------------------------- 15.5/15.5 MB 72.5 MB/s eta 0:00:00
Downloading pandas-2.1.1-cp312-cp312-win_amd64.whl (10.5 MB)
   ---------------------------------------- 10.5/10.5 MB 72.5 MB/s eta 0:00:00
Downloading scikit_learn-1.3.1-cp312-cp312-win_amd64.whl (9.1 MB)
   ---------------------------------------- 9.1/9.1 MB 73.0 MB/s eta 0:00:00
Downloading scipy-1.11.3-cp312-cp312-win_amd64.whl (43.7 MB)
   ---------------------------------------- 43.7/43.7 MB 73.1 MB/s eta 0:00:00
Downloading setuptools-68.2.2-py3-none-any.whl (807 kB)
   ---------------------------------------- 807.9/807.9 kB ? eta 0:00:00
Downloading statsmodels-0.14.0-cp312-cp312-win_amd64.whl (9.1 MB)
   ---------------------------------------- 9.1/9.1 MB 58.5 MB/s eta 0:00:00
Downloading urllib3-2.0.7-py3-none-any.whl (124 kB)
   ---------------------------------------- 124.2/124.2 kB ? eta 0:00:00
Downloading packaging-23.2-py3-none-any.whl (53 kB)
   ---------------------------------------- 53.0/53.0 kB ? eta 0:00:00
Downloading pytz-2023.3.post1-py2.py3-none-any.whl (502 kB)
   ---------------------------------------- 502.5/502.5 kB ? eta 0:00:00
Downloading threadpoolctl-3.2.0-py3-none-any.whl (15 kB)
Building wheels for collected packages: pmdarima
  Building wheel for pmdarima (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pmdarima (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [38 lines of output]
      <string>:15: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      Partial import of pmdarima during the build process.

      Traceback (most recent call last):
        File "<string>", line 190, in check_package_status
        File "C:\Program Files\Python312\Lib\importlib\__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1318, in _find_and_load_unlocked
      ModuleNotFoundError: No module named 'numpy'
      Requirements: ['joblib>=0.11\nCython>=0.29,!=0.29.18,!=0.29.31\nnumpy>=1.21.2\npandas>=0.19\nscikit-learn>=0.22\nscipy>=1.3.2\nstatsmodels>=0.13.2\nurllib3\nsetuptools>=38.6.0,!=50.0.0\n']
      Adding extra setuptools args
      Traceback (most recent call last):
        File "C:\Program Files\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Program Files\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Program Files\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\pc\AppData\Local\Temp\pip-build-env-lb8deii5\overlay\Lib\site-packages\setuptools\build_meta.py", line 434, in build_wheel
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\pc\AppData\Local\Temp\pip-build-env-lb8deii5\overlay\Lib\site-packages\setuptools\build_meta.py", line 419, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\pc\AppData\Local\Temp\pip-build-env-lb8deii5\overlay\Lib\site-packages\setuptools\build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\pc\AppData\Local\Temp\pip-build-env-lb8deii5\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 340, in <module>
        File "<string>", line 327, in do_setup
        File "<string>", line 210, in check_package_status
      ImportError: numpy is not installed.
      pmdarima requires numpy >= 1.16.

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pmdarima
Failed to build pmdarima
ERROR: Could not build wheels for pmdarima, which is required to install pyproject.toml-based projects

**Comment by aaronreidsmith** [comment] 2023-10-21 19:03
This is a duplicate of #560. It is because Python 3.12 is not yet supported. #561 added Python 3.12 support and we will publish as release soon.

**Closed by aaronreidsmith** 2023-10-21 19:03 UTC
Labels: duplicate, python 3.12

**Comment by aaronreidsmith** [comment] 2023-10-23 17:27
Python 3.12 support has been released: 

```bash
$ python -c 'import pmdarima; pmdarima.show_versions()'

System:
    python: 3.12.0 (main, Oct 12 2023, 00:42:11) [GCC 12.2.0]
executable: /usr/local/bin/python
   machine: Linux-6.4.16-linuxkit-aarch64-with-glibc2.36

Python dependencies:
 setuptools: 68.2.2
        pip: 23.2.1
    sklearn: 1.3.2
statsmodels: 0.14.0
      numpy: 1.26.1
      scipy: 1.11.3
     Cython: 3.0.4
     pandas: 2.1.1
     joblib: 1.3.2
   pmdarima: 2.0.4
```

**Comment by pcpankaj** [comment] 2023-10-24 16:52
Thanks and highly appreciated.

 

Best regards,

PC
