### ISSUE TITLE
v1.5.0 documentation link is broken

### ISSUE THREAD

**Issue by MaxGhenis** [alkaline-ml/pmdarima#267] opened 2019-12-13 20:11 UTC
https://alkaline-ml.com/pmdarima says:
>Documentation for other release versions of pmdarima:
[v1.5.0](http://alkaline-ml.com/pmdarima/1.5.0)

That points to http://alkaline-ml.com/pmdarima/1.5.0 which doesn't exist.

**Comment by tgsmith61591** [comment] 2019-12-13 20:20
This is a duplicate of #257. The home page of the documentation (http://alkaline-ml.com/pmdarima) is the current stable doc.

**Closed by tgsmith61591** 2019-12-13 20:20 UTC
Labels: :beetle: : bug

**Comment by tgsmith61591** [comment] 2019-12-13 20:32
It's fixed on master currently, but won't be fixed on the doc page until we cut a new release. 😞
