### ISSUE TITLE
Can't install pmdarima in Google Colaboratory

### ISSUE THREAD

**Issue by mclucksy0** [alkaline-ml/pmdarima#479] opened 2022-02-09 22:00 UTC
### Describe the bug

Today I try to install the pmdarima in google colaboratory via pip install pmdarima. But the installation process is in an endless loop. The installation cant finshed successfull. 

Last week the installation still works. 

Can anyone help me? 

Best regards
mclucksy

### To Reproduce

"pip install pmdarima" in google colaboratory

### Versions

```shell
1.8.4
```

### Expected Behavior

Successfull Installation of pmdarima in Google colaboratory

### Actual Behavior

Can't finished the Installation of pmdarima in Google colaboratory

**Comment by fabiospak** [comment] 2022-02-09 22:48
I have the same problem in Google Colaboratory.

**Comment by magusafr** [comment] 2022-02-10 02:58
Yesterday, I found the same problem. To solve this problem you should install !pip install statsmodels==0.13.1 before install !pip install pmdarima.

**Comment by mclucksy0** [comment] 2022-02-10 07:39
> Yesterday, I found the same problem. To solve this problem you should install !pip install statsmodels==0.13.1 before install !pip install pmdarima. 

It works, thank you for your fast solution.

**Comment by aaronreidsmith** [comment] 2022-02-15 17:36
I am unable to reproduce this ([here is my test notebook](https://colab.research.google.com/drive/1TM4m0nq7mj1R3yOKxYzMuw_Iq2n3S345?usp=sharing)). Given the timing of this issue, I wonder if it was a race condition caused by the release of statsmodels 0.13.2 on 2022-02-08. Since we can't reproduce, and there is a workaround for anyone who _can_ reproduce, I am going to close this issue.

**Closed by aaronreidsmith** 2022-02-15 17:36 UTC
Labels: :beetle: : bug
